### ISSUE TITLE
ADO extension: Could not find file 

### ISSUE THREAD

**Issue by danielstefanescu** [azsk/ADOScanner#623]
## Task: Azure DevOps (ADO) Security Scanner</br>
Using the task in the Azure Pipelines Pool - windows-latest image is displaying an error.

## Steps to reproduce
Add the Azure DevOps (ADO) Security Scanner task to a pipeline:
```
pool:
  vmImage: windows-latest

steps:
  - task: ADOSecurityScanner@1
    inputs:
      ADOConnectionName: 'foobar'
      OrgName: '$(System.CollectionUri)'
      ProjectNames: '$(System.TeamProject)'
      ScanFilter: 'Org_Project_User'
```

## Expected behavior</br> 
No error messages.

## Actual behavior
Add-Type : Could not find file 
'D:\a\_tasks\ADOSecurityScanner_0f42e73b-1b51-41b9-8bd2-c1a864393316\1.5.7\ps_modules\VstsTaskSdk\VstsTaskSdk.dll'.
At 
D:\a\_tasks\ADOSecurityScanner_0f42e73b-1b51-41b9-8bd2-c1a864393316\1.5.7\ps_modules\VstsTaskSdk\VstsTaskSdk.psm1:20 
char:1
+ Add-Type -LiteralPath $PSScriptRoot\VstsTaskSdk.dll
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Type], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.AddTypeCommand</br>
