### ISSUE TITLE
ADO extension: Log Analytics workspace configuration is missing. Check variables...

### ISSUE THREAD

**Issue by RohiteshThakur** [azsk/ADOScanner#624]
## ADOScanner extension failing to link itself to Log Analytics from YAML</br>

Connection failing to connect ADOScanner with Log Analytics in both classical and YAML pipeline. </br>

Steps to reproduce:
```
From Classic pipeline definition:
steps:
- task: azsdktm.ADOSecurityScanner.custom-build-task.ADOSecurityScanner@1
  displayName: 'ADO Security Scanner'
  inputs:
    ADOConnectionName: 'ADO-Scanner-service-connection'
    EnableOMSLogging: true



From YAML:
parameters:
- name: EnableOMSLogging
  type: boolean
  default: true
- name: LAWSSharedKey
  type: string
- name: lawsSubId
  type: string
  default: '<Azure Subscription ID>'
- name: lawsId
  type: string
  default: '<AzureLog Analytics Workspace ID>'
- name: lawsRGName
  type: string
  default: '<Resource Group name>'
- name: ADOViewName
  type: string
  default: 'ADOSec-Workbook'
- name: dashboardType
  type: string
  default: 'Workbook'

- name: image
  displayName: Pool Image
  type: string
  default: windows-latest
  values:
  - windows-latest
  - ubuntu-latest

variables:
- name: EnableOMSLogging
  value: true
- name: lawsSubId
  value: '<Azure Subscription ID>'
- name: lawsId
  value: '<AzureLog Analytics Workspace ID>'
- name: lawsRGName
  value: '<Resource Group name>'
- name: ADOViewName
  value: 'ADOSec-Workbook'
- name: dashboardType
  value: 'Workbook'

trigger: none  

jobs:
- job: run
  displayName: Call ADOScanner
  pool: 
    vmImage: ${{ parameters.image }}

  steps:
  - task: azsdktm.ADOSecurityScanner.custom-build-task.ADOSecurityScanner@1
    displayName: 'ADO Security Scanner'
    inputs:
      ADOConnectionName: '<ADO-Scanner-service-connection>'
      EnableOMSLogging: $(parameters.EnableOMSLogging)    # I have tried using variables as well e.g. $(EnableOMSLogging), same issue.
      LAWSSharedKey: $(parameters.LAWSSharedKey)
      lawsSubId: $(parameters.lawsSubId)
      lawsId: $(parameters.lawsId)
      lawsRGName: $(parameters.lawsRGName)
      ADOViewName: $(parameters.ADOViewName)                  
      dashboardType: $(parameters.dashboardType)

```

### Expected behavior: 
ADOScanner should connect to LA and ingest scan data into workbook.</br> 

### Actual behavior: 
The ADOScanner stage keeps thorowing:
Log Analytics workspace configuration is missing. Check variables... or  Log Analytics workspace logging is turned off

![image](https://user-images.githubusercontent.com/25726224/211039194-6fb076fd-4010-4512-a1ac-e8a5b03cb532.png)
![image](https://user-images.githubusercontent.com/25726224/211039588-2556b0ef-78f0-448b-af1a-f48c20f7b50b.png)

</br>
